version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: streams
      POSTGRES_PASSWORD: streams
      POSTGRES_DB: streams
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

volumes:
  pgdata:
  qdrant_data:
